# Generated by Django 4.0.4 on 2022-07-25 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title of post')),
                ('image', models.ImageField(upload_to='', verbose_name='Image of post')),
                ('text', models.TextField(verbose_name='Text')),
                ('create_at', models.DateField(verbose_name='Date of create')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of recipe')),
                ('cook_time', models.IntegerField(default=0, verbose_name='Time of cooking')),
                ('ingredients', models.TextField(verbose_name='Ingredients')),
                ('directions', models.TextField(verbose_name='Directions')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of food')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
                ('price', models.FloatField(verbose_name='price of food')),
                ('rating', models.IntegerField(default=0, verbose_name='raiting')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
